# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.22.0
assets:
  docker-password: yegor256/home#assets/docker-password
merge:
  script: |-
    sudo docker build "$(pwd)"
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    repo=yegor256/rultor-image
    sed -i -e "s/^0.0.0/${tag}/" Dockerfile
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    cat ../docker-password | sudo docker login --password-stdin --username yegor256
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
